// ══════════════════════════════════════════════
//  ALLERGEN DATA — Single source of truth
//  Shared across comedor.html, gestion.html, desayuno.html
// ══════════════════════════════════════════════
window.ALLERGENS = [
  { id:'gluten',     es:'GLUTEN',     en:'Gluten',      color:'#e67e22', icon:'./img/alergenos_gluten.svg', },
  { id:'crustaceos', es:'CRUSTÁCEOS', en:'Crustaceans', color:'#3498db', icon:'./img/alergenos_crustaceos.svg', },
  { id:'huevos',     es:'HUEVOS',     en:'Eggs',        color:'#f39c12', icon:'./img/alergenos_huevos.svg', },
  { id:'pescado',    es:'PESCADO',    en:'Fish',        color:'#2c3e50', icon:'./img/alergenos_pescado.svg', },
  { id:'cacahuetes', es:'CACAHUETES', en:'Peanuts',     color:'#d35400', icon:'./img/alergenos_cacahuetes.svg', },
  { id:'soja',       es:'SOJA',       en:'Soy',         color:'#27ae60', icon:'./img/alergenos_soja.svg', },
  { id:'lacteos',    es:'LÁCTEOS',    en:'Dairy',       color:'#5d4037', icon:'./img/alergenos_lacteos.svg', },
  { id:'cascara',    es:'F.CÁSCARA',  en:'Tree nuts',   color:'#c0392b', icon:'./img/alergenos_cascara.svg', },
  { id:'apio',       es:'APIO',       en:'Celery',      color:'#8bc34a', icon:'./img/alergenos_apio.svg', },
  { id:'mostaza',    es:'MOSTAZA',    en:'Mustard',     color:'#b8860b', icon:'./img/alergenos_mostaza.svg', },
  { id:'sesamo',     es:'SÉSAMO',     en:'Sesame',      color:'#7f8c8d', icon:'./img/alergenos_sesamo.svg', },
  { id:'sulfitos',   es:'SULFITOS',   en:'Sulphites',   color:'#8e44ad', icon:'./img/alergenos_sulfitos.svg', },
  { id:'moluscos',   es:'MOLUSCOS',   en:'Molluscs',    color:'#1abc9c', icon:'./img/alergenos_moluscos.svg', },
  { id:'altramuces', es:'ALTRAMUCES', en:'Lupins',      color:'#f1c40f', icon:'./img/alergenos_altramuces.svg', }
];

// Índice por id para evitar llamadas a .find() en bucles (14 alérgenos x plato).
window.ALLERGEN_BY_ID = Object.fromEntries(window.ALLERGENS.map(a => [a.id, a]));

window.CORRECTOR_PLATOS = {
  'berlina': 'doughnut',
  'tortilla española': 'Spanish omelette',
  'tortilla de patatas': 'Spanish omelette',
  'croqueta': 'croquette', 'croquetas': 'croquettes',
  'empanadilla': 'pastry', 'empanadillas': 'pastries',
  'alitas de pollo': 'chicken wings',
  'filete': 'steak', 'hamburguesa': 'burger', 'hamburguesas': 'burgers',
  'bocadillo': 'sandwich', 'bocadillos': 'sandwiches',
  'patatas fritas': 'fries', 'patatas bravas': 'spicy potatoes',
  'pimientos de padrón': 'padron peppers',
  'jamón serrano': 'serrano ham', 'jamón ibérico': 'iberian ham',
  'chorizo': 'chorizo', 'salchicha': 'sausage',
  'calamares': 'squid rings', 'gamba': 'prawn', 'gambas': 'prawns',
  'langostino': 'prawn', 'mejillón': 'mussel', 'mejillones': 'mussels',
  'bacalao': 'cod', 'merluza': 'hake',
  'dorada': 'sea bream', 'lubina': 'sea bass',
  'pollo': 'chicken', 'pavo': 'turkey', 'cordero': 'lamb',
  'ternera': 'beef', 'cerdo': 'pork', 'conejo': 'rabbit',
  'lomo': 'loin', 'solomillo': 'tenderloin',
  'albóndigas': 'meatballs',
  'alboronico': 'fennel',
  'judías verdes con tomate': 'green beans in tomato sauce',
  'judías verdes': 'green beans',
  'garbanzos': 'chickpeas', 'lentejas': 'lentils',
  'guisantes': 'peas', 'maíz': 'sweetcorn',
  'champiñones': 'mushrooms', 'setas': 'mushrooms',
  'pimiento': 'pepper', 'calabacín': 'courgette',
  'berenjena': 'aubergine',
  'coliflor': 'cauliflower', 'brócoli': 'broccoli',
  'espinacas': 'spinach', 'acelgas': 'chard',
  'lechuga': 'lettuce', 'cebolla': 'onion', 'ajo': 'garlic',
  'zanahoria': 'carrot', 'pepino': 'cucumber',
  'tomate': 'tomato',
  'repollo': 'cabbage',
  'rúcula': 'rocket',
  'espárragos': 'asparagus', 'alcachofa': 'artichoke',
  'perejil': 'parsley', 'cilantro': 'coriander',
  'albahaca': 'basil', 'romero': 'rosemary',
  'tomillo': 'thyme', 'orégano': 'oregano',
  'menta': 'mint', 'lavanda': 'lavender',
  'laurel': 'bay leaf', 'canela': 'cinnamon',
  'nuez moscada': 'nutmeg', 'clavo': 'clove',
  'pimienta': 'black pepper', 'ajo': 'garlic',
  'aceite de oliva': 'olive oil', 'vinagre': 'vinegar',
  'caldo': 'stock', 'sopa': 'soup', 'puré': 'purée',
  'guiso': 'stew', 'salteado': 'stir-fry',
  'al horno': 'baked', 'a la plancha': 'grilled',
  'frito': 'fried', 'hervido': 'boiled',
  'al vapor': 'steamed', 'asado': 'roasted',
  'a la parrilla': 'grilled', 'al ajillo': 'garlic',
  'a la romana': 'Roman-style',
  'a la madrileña': 'Madrid-style',
  'a la catalana': 'Catalan-style',
  'a la valenciana': 'Valencian-style',
  'con tomate': 'in tomato sauce',
  'con salsa': 'in sauce', 'en salsa': 'in sauce',
  'a la': 'style', 'con': 'with',
  'pudding': 'pudding', 'muffin': 'muffin',
  'tostada con tomate': 'tomato toast',
  'pan con tomate': 'tomato bread',
  'pa amb tomàquet': 'tomato bread',
  'pan': 'bread', 'pan integral': 'wholemeal bread',
  'croissant': 'croissant', 'churro': 'churro',
  'tarta': 'cake', 'torta': 'cake',
  'galleta': 'biscuit', 'galletas': 'biscuits',
  'helado': 'ice cream',
  'helado de frutos del bosque': 'wild berry ice cream',
  'helado de chocolate': 'chocolate ice cream',
  'helado de vainilla': 'vanilla ice cream',
  'helado de fresa': 'strawberry ice cream',
  'helado de limón': 'lemon sorbet',
  'helado de menta': 'mint ice cream',
  'helado de coco': 'coconut ice cream',
  'helado de mango': 'mango ice cream',
  'helado de café': 'coffee ice cream',
  'helado de pistacho': 'pistachio ice cream',
  'helado de caramelo': 'caramel ice cream',
  'helado de caramelo salado': 'salted caramel ice cream',
  'helado de frambuesa': 'raspberry ice cream',
  'helado de arándano': 'blueberry ice cream',
  'helado de mora': 'blackberry ice cream',
  'helado de durazno': 'peach ice cream',
  'helado de albaricoque': 'apricot ice cream',
  'helado de ciruela': 'plum ice cream',
  'helado de manzana': 'apple ice cream',
  'helado de pera': 'pear ice cream',
  'helado de kiwi': 'kiwi ice cream',
  'sorbete': 'sorbet',
  'ensalada': 'garden salad',
  'ensalada mixta': 'mixed salad',
  'ensalada verde': 'green salad',
  'ensalada de fruta': 'fruit salad',
  'ensalada de garbanzos': 'chickpea salad',
  'ensalada de patata': 'potato salad',
  'ensalada de atún': 'tuna salad',
  'ensalada de gambas': 'prawn salad',
  'fruta': 'fresh fruit',
  'zumo': 'fresh juice',
  'agua': 'water',
  'mantequilla': 'butter', 'nata': 'cream',
  'queso': 'cheese', 'queso cheddar': 'cheddar',
  'queso manchego': 'manchego',
  'yogur': 'yoghurt',
  'huevo': 'egg', 'huevos': 'eggs',
  'harina': 'flour', 'azúcar': 'sugar',
  'cúrcuma': 'turmeric', 'comino': 'cumin',
  'azafrán': 'saffron', 'pimentón': 'paprika',
  'café': 'coffee', 'café con leche': 'coffee with milk',
  'café solo': 'espresso',
  'vino': 'wine', 'vino tinto': 'red wine', 'vino blanco': 'white wine',
  'cerveza': 'beer', 'cava': 'cava',
  'dulce de leche': 'dulce de leche', 'dulce de naranja': 'orange marmalade',
  'miel': 'honey', 'sirope': 'syrup',
  'tortilla de huevo': 'omelette',
  'judía': 'bean', 'judías': 'beans',
  'garbanzo': 'chickpea',
  'lentejas': 'lentils',
  'garbanzos': 'chickpeas',
};

window.CORRECTOR_INGLES = {
  'sedans': 'doughnuts',
  'sedan': 'doughnut',
  'sedans filled': 'doughnuts filled',
  'sedan filled': 'doughnut filled',
};
